### ISSUE TITLE
can not access http://rexrayconfig.emccode.com

### ISSUE THREAD

**Issue by wangzhizheng** [kacole2/rexray-config-generator#33]
the url is now directed to http://codedellemc.com/

**Comment by kacole2** [comment]
@wangzhizeng will get that fixed today. I knew some things would be forgotten during the cutover.

**Comment by kacole2** [comment]
@wangzhizheng the new url is [http://rexrayconfig.codedellemc.com/](http://rexrayconfig.codedellemc.com/). Had to update completely and couldn't put in a forwarding rule. #34 updates the docs
